### ISSUE TITLE
[Fixed] Protection Mission

### ISSUE THREAD

**Issue by tdmike** [GhostRolly/red_house#1]
Up in Downtown Vinewood one of the protection missions, the VIP is spawned underground (I Checked with EnchancedTrainer), normally the mission can't be started. And it can't be cancelled, the key combination for cancellation does not work. I'm currently looking if I can solve it myself, any idea what is going wrong ?

Update: Not sure if I'm correct but it seems that there is no cancellation implemented yet.

Also is it and idea to put a full readme on Github ?

**Comment by GhostRolly** [comment]
Hi, I'll see if I screwed up somewhere with the coordinates.
By the way, to cancel a mission, you have to press O (the letter O).
I omitted to tell it on the read me.

Let me see if I can fix it for ya :)

**Comment by tdmike** [comment]
Hey, Ah well, that explains a lot I thought it was the number zero. If you need any help just mention me, I know a little C++ :)

**Comment by GhostRolly** [comment]
I was probably drunk when I wrote this : 

int myRand = (rand() % 17) + 2;

It is used to randomly find a value. 
The problem is I only have 15 missions of protection contracts.
So at some point, it goes to 19 and well... It laggs out and place a random point in the map.
Fixed it by doing this : 

int myRand = rand() % 15;

**Comment by tdmike** [comment]
Hahaha, well at least  you manage to write code while drunk, I can barely boot up my pc. Anyway I'll recompile and check if it is fixed.

**Comment by tdmike** [comment]
Seems I can't recompile your sln, it's missing main.h and natives.h which should be placed in inc\

**Comment by GhostRolly** [comment]
Changed 2-3 things, should compile now.

**Comment by tdmike** [comment]
I closed this issue, works fine now
